server:
  port: ${PORT:58090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

enterprise:
  channel: ${ENTERPRISE_CHANNEL:enterprise-out-0}

spring:
  application:
    name: sage-ms-enterprise
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      read_unknown_enum_values_as_null: true
      fail_on_unknown_properties: false
  cloud.stream:
    bindings:
      enterprise-out-0:
        destination: enterprise
        binder: kafka
      negotiation-in-0:
        destination: negotiation
        binder: rabbit
        consumer.exchangeType: direct
    binders:
      kafka:
        type: kafka
        environment.spring.cloud.stream.kafka.binder.brokers: localhost:9092
      rabbit:
        type: rabbit
        environment.spring.rabbitmq.host: localhost
    function:
      definition: negotiation
    main:
      allow-bean-definition-overriding: true

  management:
    endpoint:
      health:
        show-components: always
        show-details: always
    health:
      rabbit:
        enabled: false
      binders:
        enabled: true


