spring:
  cloud:
    gateway:
      httpclient:
        response-timeout: 5m
      actuator:
        verbose:
          enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: enterprises
          uri: lb://${ENTERPRISE_SERVICE:sage-ms-enterprise}/enterprises
          predicates:
            - Path=/enterprises/**
        - id: negotiation
          uri: lb://${NEGOTIATION_SERVICE:sage-ms-negotiation}/negotiations
          predicates:
            - Path=/negotiations/**

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints.web.exposure.include: '*'

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true