spring:
  cloud:
    gateway:
      httpclient:
        response-timeout: 5m
      actuator:
        verbose:
          enabled: true
      routes:
        - id: enterprises
          uri: ${ENTERPRISE_SERVICE:http://sage-ms-enterprise}/enterprises
          predicates:
            - Path=/enterprises/**
        - id: negotiation
          uri: ${NEGOTIATION_SERVICE:http://sage-ms-negotiation}/negotiations
          predicates:
            - Path=/negotiations/**

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints.web.exposure.include: '*'